<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-05T23:41:00 IST" name="Suite" finished-at="2023-07-05T23:41:32 IST" duration-ms="31443">
    <groups>
    </groups>
    <test started-at="2023-07-05T23:41:00 IST" name="Test" finished-at="2023-07-05T23:41:32 IST" duration-ms="31443">
      <class name="TestCases.LoginTestCase">
        <test-method is-config="true" signature="launchBrowserURL()[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:00 IST" name="launchBrowserURL" finished-at="2023-07-05T23:41:05 IST" duration-ms="4811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserURL -->
        <test-method signature="verifyLogin(java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:05 IST" name="verifyLogin" data-provider="testData" finished-at="2023-07-05T23:41:06 IST" duration-ms="713" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secure123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Locator must be set]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Locator must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:342)
at PageObjectModel.loginpageobjects.errorMessage(loginpageobjects.java:42)
at TestCases.LoginTestCase.verifyLogin(LoginTestCase.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="launchBrowserURL()[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:06 IST" name="launchBrowserURL" finished-at="2023-07-05T23:41:09 IST" duration-ms="3356" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserURL -->
        <test-method signature="verifyLogin(java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:09 IST" name="verifyLogin" data-provider="testData" finished-at="2023-07-05T23:41:11 IST" duration-ms="1222" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[roahn]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secure456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Locator must be set]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Locator must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:342)
at PageObjectModel.loginpageobjects.errorMessage(loginpageobjects.java:42)
at TestCases.LoginTestCase.verifyLogin(LoginTestCase.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="launchBrowserURL()[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:11 IST" name="launchBrowserURL" finished-at="2023-07-05T23:41:14 IST" duration-ms="3093" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserURL -->
        <test-method signature="verifyLogin(java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTestCase@7cc0cdad]" started-at="2023-07-05T23:41:14 IST" name="verifyLogin" data-provider="testData" finished-at="2023-07-05T23:41:15 IST" duration-ms="1512" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secure789]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Locator must be set]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Locator must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:342)
at PageObjectModel.loginpageobjects.errorMessage(loginpageobjects.java:42)
at TestCases.LoginTestCase.verifyLogin(LoginTestCase.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
      </class> <!-- TestCases.LoginTestCase -->
      <class name="TestCases.SignupTestCases">
        <test-method is-config="true" signature="launchBrowserURL()[pri:0, instance:TestCases.SignupTestCases@1d296da]" started-at="2023-07-05T23:41:15 IST" name="launchBrowserURL" finished-at="2023-07-05T23:41:18 IST" duration-ms="3164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowserURL -->
        <test-method signature="verifySignup()[pri:0, instance:TestCases.SignupTestCases@1d296da]" started-at="2023-07-05T23:41:18 IST" name="verifySignup" finished-at="2023-07-05T23:41:32 IST" duration-ms="13482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySignup -->
      </class> <!-- TestCases.SignupTestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
